---
title: "PlaybyPlay_EDA"
output: html_document
date: "2023-09-15"
---

```{r}
library(tidyverse)
library(ggrepel)
library(nflreadr)
library(nflplotR)
```
```{r}
data <- load_pbp(2022)
head(data)

data %>%
  group_by(play_type) %>%
  summarize(n = n())
```

```{r}
qbs <- data %>%
  filter(season_type == "REG", !is.na(epa)) %>%
  group_by(id, name) %>%
  summarize(
    epa = mean(qb_epa),
    cpoe = mean(cpoe, na.rm = T),
    n_dropbacks = sum(pass),
    n_plays = n(),
    team = last(posteam)
  ) %>%
  ungroup() %>%
  filter(n_dropbacks > 50 & n_plays > 500)

qbs <- qbs %>%
  left_join(load_teams(), by = c('team' = 'team_abbr'))
```

```{r}
qbs %>%
  ggplot(aes(x = cpoe, y = epa)) +
  #horizontal line with mean EPA
  geom_hline(yintercept = mean(qbs$epa), color = "red", linetype = "dashed", alpha=0.5) +
  #vertical line with mean CPOE
  geom_vline(xintercept =  mean(qbs$cpoe), color = "red", linetype = "dashed", alpha=0.5) +
  #add points for the QBs with the logos (this uses nflplotR package)
  geom_nfl_logos(aes(team_abbr = team), width = qbs$n_plays / 45000, alpha = 0.75) +
  #add names using ggrepel, which tries to make them not overlap
  geom_text_repel(aes(label=name)) +
  #add a smooth line fitting cpoe + epa
  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+
  #titles and caption
  labs(x = "Completion % above expected (CPOE)",
       y = "EPA per play (passes, rushes, and penalties)",
       title = "Quarterback Efficiency, 2022",
       caption = "Data: @nflfastR") +
  theme_bw() +
  #center title
  theme(
    plot.title = element_text(size = 14, hjust = 0.5, face = "bold")
  ) +
  #make ticks look nice
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))
```
```{r}
knitr::kable(nflreadr::dictionary_ftn_charting)
knitr::kable(nflreadr::dictionary_pbp)
```



```{r}
ftndata2022 <- nflreadr::load_ftn_charting(2022)

ftndata2022 %>% 
  ggplot(aes(n_blitzers, n_pass_rushers)) + 
  geom_point()
```
```{r}
data2022 <- nflreadr::load_pbp(2022) 
ftndata2022 <- nflreadr::load_ftn_charting(2022)

data2023 <- nflreadr::load_pbp(2023) 
ftndata2023 <- nflreadr::load_ftn_charting(2023)

data2022
```

